[package]
name = "get_mirror_data"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
mif = "0.3.0"
minidom = "0.13.0"
serde = "1.0.126"
serde_json = "1.0.64"
